checklistManager:
  image: checklist-app
  tag:
  pullPolicy: IfNotPresent
  portName: http
  port: 8080
  protocol: TCP
  replicaCount: 1
  liveness:
    endpoint: /checklist-manager/mgmt/health/liveness
    initialDelaySeconds: 20
    periodSeconds: 60
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readiness:
    endpoint: /checklist-manager/mgmt/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

postgres:
  name: "postgres"
  enabled: true
  image: postgres
  tag: "15"
  pullPolicy: IfNotPresent
  replicaCount: 1
  db:
    dbName: checklist_db
    schema: "checklist_schema"
    host: "postgres"
    user: checklist
  port: 5432
  portName: http
  protocol: TCP
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

secrets:
  secretKey: jdxZxb9Wkt/x5Bw9726ecQ81Bibb.cxdiV1reCgrzFadnA8g5DOLTwEnOEXnhBD1u
  secretExpiration: 3600
  dbPassword: checklist
