services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: checklist_db
      POSTGRES_USER: checklist
      POSTGRES_PASSWORD: checklist
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U checklist" ]
      interval: 10s
      timeout: 5s
      retries: 5
  checklist:
    build:
      dockerfile: Dockerfile
    image: checklist-app
    environment:
      SCHEMA_DB: checklist_schema
      DB_NAME: checklist_db
      DB_HOST: postgres
      DB_USER: checklist
      DB_PASSWORD: checklist
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - "8080:8080"

