apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/name: checklist-app

spec:
  replicas: {{ .Values.checklistManager.replicaCount }}
  selector:
    matchLabels:
      app: checklist-app
  template:
    metadata:
      labels:
        app: checklist-app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.checklistManager.image }}:{{ .Values.checklistManager.tag | default "latest" }}
        imagePullPolicy: {{ .Values.postgres.pullPolicy }}
        ports:
        - name: {{ .Values.checklistManager.portName | default "http" }}
          containerPort: {{ .Values.checklistManager.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            port: {{ .Values.checklistManager.port }}
            path: {{ .Values.checklistManager.liveness.endpoint }}
          initialDelaySeconds: {{ .Values.checklistManager.liveness.initialDelaySeconds | default 20 }}
          periodSeconds: {{ .Values.checklistManager.liveness.periodSeconds | default 60 }}
          timeoutSeconds: {{ .Values.checklistManager.liveness.timeoutSeconds | default 10 }}
          successThreshold: {{ .Values.checklistManager.liveness.successThreshold | default 1 }}
          failureThreshold: {{ .Values.checklistManager.liveness.failureThreshold | default 3 }}
        readinessProbe:
          httpGet:
            port: {{ .Values.checklistManager.port }}
            path: {{ .Values.checklistManager.readiness.endpoint }}
          initialDelaySeconds: {{ .Values.checklistManager.readiness.initialDelaySeconds | default 20 }}
          periodSeconds: {{ .Values.checklistManager.readiness.periodSeconds | default 10 }}
          timeoutSeconds: {{ .Values.checklistManager.readiness.timeoutSeconds | default 5 }}
          successThreshold: {{ .Values.checklistManager.readiness.successThreshold | default 1 }}
          failureThreshold: {{ .Values.checklistManager.readiness.failureThreshold | default 1 }}
        env:
          - name: DB_SCHEMA
            valueFrom:
              configMapKeyRef:
                name: checklist-manager-config
                key: DB_SCHEMA
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: checklist-manager-config
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: checklist-manager-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: checklist-manager-config
                key: DB_USER
          - name:  DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: checklist-manager-secret
                key: POSTGRES_PASSWORD
          - name:  API_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: checklist-manager-secret
                key: API_SECRET_KEY
          - name: API_SECRET_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: checklist-manager-secret
                key: API_SECRET_EXPIRATION
        resources:
          {{ toYaml .Values.checklistManager.resources | nindent 12 }}
      automountServiceAccountToken: false
