apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app.kubernetes.io/instance: {{ .Values.postgres.name }}

spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag | default "latest" }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: checklist-manager-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: checklist-manager-config
              key: DB_USER
        - name:  POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: checklist-manager-secret
              key: POSTGRES_PASSWORD
        resources:
          {{ toYaml .Values.postgres.resources | nindent 12 }}
      automountServiceAccountToken: false
