apiVersion: v1
kind: Secret
metadata:
  name: checklist-manager-secret
type: Opaque
stringData:
  API_SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  API_SECRET_EXPIRATION: {{ .Values.secrets.secretExpiration | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}