openapi: 3.0.3
info:
    title: DevOps Checklist
    description: A checklist for DevOps practices and tools.
    version: 1.0.0

paths:
  /checklist:
    get:
      summary: Get all checklists
      operationId: getCheckLists
      responses:
        '200':
          description: List of checklists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistDto'
    post:
      summary: Create a new checklist
      operationId: createChecklist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChecklistDto'
      responses:
        '201':
          description: Checklist created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistDto'
components:
  schemas:
    ChecklistDto:
      type: object
      properties:
        title:
            type: string
            description: Title of the checklist
        environment:
            type: string
            description: Environment of the checklist
        version:
            type: string
            description: Version of the checklist
        tags:
            type: array
            items:
                type: string
            description: Tags associated with the checklist
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChecklistItemDto'
    ChecklistItemDto:
      type: object
      properties:
        description:
            type: string
            description: Description of the checklist item
        status:
          type: string
          enum: [PENDING, DONE, COMPLETED]
          description: Status of the checklist item