openapi: 3.0.3
info:
    title: DevOps Checklist
    description: A checklist for DevOps practices and tools.
    version: 1.0.0

paths:
  /checklist:
    get:
      tags:
        - ChecklistManager
      summary: Get all checklists
      operationId: getCheckLists
      responses:
        '200':
          description: List of checklists
          content:
            application/checklist-v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistDto'
    post:
      tags:
        - ChecklistManager
      summary: Create a new checklist
      operationId: createChecklist
      requestBody:
        required: true
        content:
          application/checklist-request-v1+json:
            schema:
              $ref: '#/components/schemas/ChecklistDto'
      responses:
        '201':
          description: Checklist created successfully
          content:
            application/checklist-v1+json:
              schema:
                $ref: '#/components/schemas/ChecklistDto'
  /checklist/{id}:
    put:
      tags:
        - ChecklistManager
      summary: Update checklist
      operationId: updateChecklist
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the checklist to update
          schema:
            type: string
      responses:
        '200':
          description: Checklist updated successfully
          content:
            application/checklist-v1+json:
              schema:
                $ref: '#/components/schemas/ChecklistDto'
components:
  schemas:
    ChecklistDto:
      type: object
      properties:
        id:
            type: string
            description: Unique identifier for the checklist
        title:
            type: string
            description: Title of the checklist
        environment:
            type: string
            description: Environment of the checklist
        version:
            type: string
            description: Version of the checklist
        tags:
            type: array
            items:
                $ref: '#/components/schemas/ChecklistTagDto'
            description: Tags associated with the checklist
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChecklistItemDto'
        createdAt:
            type: string
            format: date-time
            description: Creation date of the checklist
        updatedAt:
            type: string
            format: date-time
            description: Last update date of the checklist
    ChecklistItemDto:
      type: object
      properties:
        description:
            type: string
            description: Description of the checklist item
        status:
          type: string
          enum: [PENDING, DONE, BLOCKED]
          description: Status of the checklist item
    ChecklistTagDto:
      type: object
      properties:
        tag:
          type: string
          description: Tag of the checklist