name: CI - Helm Chart Integration Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  helm-chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set VERSION variable
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kind
        uses: helm/kind-action@v1.7.0

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Helm Chart
        run: helm lint ./chart/

      - name: Build Docker image
        run: docker build --file Dockerfile --tag checklist-app:$VERSION .

      - name: Load Docker image into Kind
        run: |
          kind load docker-image checklist-app:$VERSION --name chart-testing

      - name: Helm Install
        run: |
          helm install checklist ./chart/. \
            --kube-context kind-chart-testing \
            --set checklistManager.tag=$VERSION \
            --wait
          kubectl get pods --context kind-chart-testing
          kubectl port-forward svc/checklist-manager-service 8080:80  --context kind-chart-testing &
          sleep 10
          curl --fail http://localhost:8080/checklist-manager/mgmt/health

      - name: Diagnose Failure (pods, events, describe)
        if: always()
        run: |
          echo "=== Pods ==="
          kubectl get pods -A
          echo "=== Events ==="
          kubectl get events -A --sort-by=.metadata.creationTimestamp
          echo "=== Describe Checklist Pods ==="
          kubectl describe pods -l app=checklist-app -A || true
          echo ""=== Get Logs from Checklist Pod ===""
          kubectl logs -l app=checklist-app --context kind-chart-testing || true
          kubectl logs -l app=checklist-app -c init-schema --context kind-chart-testing || true
          kubectl logs -l app=postgres --context kind-chart-testing || true
