name: CI - Helm Chart Integration Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  helm-chart-test:
    runs-on: ubuntu-latest
    env:
      VERSION: $(date +%s)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kind
        uses: helm/kind-action@v1.7.0

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Helm Chart
        run: helm lint ./chart/

      - name: Build Docker image
        run: docker build --file Dockerfile --tag checklist-app:$VERSION .

      - name: Load Docker image into Kind
        run: |
          kind load docker-image checklist-app:$VERSION

      - name: Helm Install
        run: |
          helm install checklist ./chart/. \
            --set checklistManager.tag=$VERSION \
            --wait
          kubectl get pods
          kubectl port-forward svc/checklist-service 8080:80 &
          sleep 10
          curl --fail http://localhost:8080/checklist-manager/actuator/health

      - name: Diagnose Failure (pods, events, describe)
        if: always()
        run: |
          echo "=== Pods ==="
          kubectl get pods -A
          echo "=== Events ==="
          kubectl get events -A --sort-by=.metadata.creationTimestamp
          echo "=== Describe Checklist Pods ==="
          kubectl describe pods -l app.kubernetes.io/name=checklist-app -A || true
