name: CI - Docker Compose Integration Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-compose-integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag checklist-app

      - name: Build and run with Docker Compose
                - name: Build the Docker image
        run: |
          docker compose up --build -d

      - name: Wait for the checklist service to be ready
        run: |
          echo "Waiting for checklist service..."
          until curl --fail http://localhost:8080/checklist-manager/mgmt/health; do
            sleep 5
          done

      - name: Shut down Docker Compose
        if: always()
        run: docker compose down
